// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqAaTcs-iM7gt2-FmfDqgH-u_uQBcb_w',
    appId: '1:241072538063:web:b7ee7fd053890cb25e92ba',
    messagingSenderId: '241072538063',
    projectId: 'paliodash-f9917',
    authDomain: 'paliodash-f9917.firebaseapp.com',
    storageBucket: 'paliodash-f9917.firebasestorage.app',
    measurementId: 'G-P21YJH4V67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQoNrbc27-X3PIii3X8_Ij6VpJbv4XXsc',
    appId: '1:241072538063:android:7fd167e4373fd0825e92ba',
    messagingSenderId: '241072538063',
    projectId: 'paliodash-f9917',
    storageBucket: 'paliodash-f9917.firebasestorage.app',
  );
}
